import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {Window} from 'happy-dom';
const q=(id,code,type='text')=>({item_key:id,section_code:code,section_name:code==='A'?'기본정보':'상품',item_label:id==='A-01'?'농가 이름':id==='F-01'?'상품 규격':id,plain_question:id==='A-01'?'농가 이름을 알려주세요.':id,options:'',input_type:type,required_level:id==='A-01'?'REQUIRED':'REVIEW'});
const catalog=[...Array.from({length:8},(_,i)=>q('A-0'+(i+1),'A')),q('F-01','F'),{...q('H-01','H','multiselect'),options:'["월요일","화요일"]'}];
const deck={deck_id:'CODE1_AZA_INTERNAL',version:0,version_label:'v0.0',slides:[{slide_id:'s1',width:1920,height:1080,background:{color:'#ffffff',fit:'cover',position:'center',opacity:1,overlayColor:'#000000',overlayOpacity:0,zoom:1},elements:[]}]};
// A DOM-level interaction test, not a browser layout or real Google API test.
async function fixture(options={}){const w=new Window({url:'https://qa.example.test',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});const errors=[];w.addEventListener('error',e=>errors.push(e.message));w.ResizeObserver=class{observe(){} disconnect(){}};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};let saved,saveCalls=0;
 const permissions=options.permissions||{farm:'edit',deck:'edit',farmIds:[],allFarms:true,accounts:true,review:true};const boot={user:{id:'owner',username:'owner',displayName:'테스트 관리자',email:'qa@example.test',role:options.role||'SUPER_ADMIN',version:1,permissions,hasPassword:false},permissions,canEditDeck:permissions.deck==='edit',catalog,farms:[{id:'f1',name:'가상 농가'}],submissions:[],deck:permissions.deck==='none'?null:deck,settings:null};
 w.fetch=async(url,init)=>{if(url==='/api/accounts')return {ok:true,json:async()=>({data:{accounts:[boot.user],farms:boot.farms}})};if(url==='/api/session')return {json:async()=>({configured:true,authenticated:true})};const {action,payload:p}=JSON.parse(init.body);let data;if(action==='bootstrap')data=boot;if(action==='deckAssets')data={};if(action==='saveSubmission'){saveCalls++;saved={...p,revision:p.baseRevision+1,farmId:'f1',media:[]};data=saved;boot.submissions=[{id:p.id,name:p.name,farmId:'f1',status:p.status,revision:saved.revision}];}if(action==='getSubmission')data=saved;if(action==='saveDeck'){boot.deck={...p.deck,version:p.baseVersion+1};data={version:boot.deck.version,versionLabel:'v0.1'};}return {ok:true,json:async()=>({data})};};
 w.document.write(fs.readFileSync('public/index.html','utf8').replace(/<script[^>]*><\/script>/g,''));for(const p of ['core.js','farm-model.js','accounts.js','app.js'])w.eval(fs.readFileSync('public/assets/'+p,'utf8'));await w.happyDOM.waitUntilComplete();return {w,errors,calls:()=>saveCalls};}
const click=(w,id)=>w.document.getElementById(id).click();
const input=(w,id,value)=>{const n=w.document.getElementById(id);n.value=value;n.dispatchEvent(new w.Event('input',{bubbles:true}));};
test('farm UI groups and pages questions, searches globally, autosaves, summarizes and excludes completed requests',async()=>{const {w,errors,calls}=await fixture();try{assert.deepEqual(errors,[]);const d=w.document;assert.equal(d.getElementById('farm-page').hidden,false);d.querySelector('#farm-list button').click();await w.happyDOM.waitUntilComplete();assert.equal(d.querySelectorAll('#categories button').length,6);assert.equal(d.querySelectorAll('#question-form .question').length,5);input(w,'q-A-02','추가 답변');await w.happyDOM.waitUntilComplete();assert.ok(calls()>0);assert.match(d.getElementById('save-status').textContent,/저장됨/);input(w,'question-search','상품 규격');assert.equal(d.querySelectorAll('#question-form .question').length,1);assert.ok(d.getElementById('q-F-01'));click(w,'answer-summary');assert.match(d.getElementById('summary-content').textContent,/추가 답변/);click(w,'close-summary');click(w,'request-pdf');assert.equal(d.querySelector('#request-items input[value="A-01"]'),null);assert.equal(d.querySelector('#request-items input[value="A-02"]'),null);assert.ok(d.querySelector('#request-items input[value="F-01"]'));click(w,'request-select-none');assert.equal(d.getElementById('request-download').disabled,true);assert.deepEqual(errors,[]);}finally{await w.happyDOM.close();}});
test('deck edit text uses side panel, undo/redo restores content, ordinary save has no prompt',async()=>{const {w,errors}=await fixture();try{const d=w.document;d.querySelector('[data-page="deck"]').click();click(w,'edit-mode');click(w,'add-text');const box=d.querySelector('#property-fields textarea');assert.ok(box);box.value='바뀐 제안서 제목';box.dispatchEvent(new w.Event('change',{bubbles:true}));assert.match(d.getElementById('slide-canvas').textContent,/바뀐 제안서 제목/);click(w,'undo');assert.doesNotMatch(d.getElementById('slide-canvas').textContent,/바뀐 제안서 제목/);click(w,'redo');assert.match(d.getElementById('slide-canvas').textContent,/바뀐 제안서 제목/);let prompts=0;w.prompt=()=>{prompts++;return null;};click(w,'deck-save');await w.happyDOM.waitUntilComplete();assert.equal(prompts,0);assert.match(d.getElementById('deck-saved').textContent,/저장됨/);assert.deepEqual(errors,[]);}finally{await w.happyDOM.close();}});
test('farm-only account hides deck and admin pages; read-only controls cannot autosave',async()=>{const {w,errors,calls}=await fixture({role:'FARMER',permissions:{farm:'view',deck:'none',farmIds:['f1'],allFarms:false,accounts:false,review:false}});try{const d=w.document;assert.equal(d.querySelector('#main-nav [data-page="deck"]').hidden,true);assert.equal(d.getElementById('new-farm').hidden,true);d.querySelector('#farm-list button').click();await w.happyDOM.waitUntilComplete();assert.equal(d.getElementById('q-A-01').disabled,true);assert.equal(d.getElementById('draft-save').disabled,true);assert.equal(d.getElementById('review-panel').hidden,true);d.querySelector('#main-nav [data-page="deck"]').click();assert.equal(d.getElementById('deck-page').hidden,true);click(w,'accounts-nav');assert.equal(d.getElementById('account-management').hidden,true);assert.equal(calls(),0);assert.deepEqual(errors,[]);}finally{await w.happyDOM.close();}});
test('top admin can choose menu levels and farm assignments when creating an account',async()=>{const {w,errors}=await fixture();try{const d=w.document;click(w,'accounts-nav');await w.happyDOM.waitUntilComplete();assert.equal(d.getElementById('account-management').hidden,false);click(w,'add-account');await w.happyDOM.waitUntilComplete();assert.equal(d.getElementById('account-dialog').open,true);assert.equal(d.getElementById('account-role').value,'FARMER');assert.equal(d.getElementById('permission-deck').value,'none');assert.equal(d.querySelectorAll('#account-farms input:checked').length,0);d.getElementById('account-role').value='ADMIN';d.getElementById('account-role').dispatchEvent(new w.Event('change'));assert.equal(d.getElementById('account-permissions').hidden,true);assert.equal(d.getElementById('admin-access-note').hidden,false);assert.deepEqual(errors,[]);}finally{await w.happyDOM.close();}});
