import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {sign,verify,session,sameOrigin,bridge,hmac} from '../functions/_shared/security.js';
import {onRequestPost} from '../functions/api/rpc.js';
const model=vm.createContext({});vm.runInContext(await readFile('public/assets/farm-model.js','utf8'),model);
const F=model.Code1Farm;
const catalog=[{item_key:'A',section_code:'A',item_label:'농가 이름',input_type:'text'},{item_key:'N',section_code:'G',item_label:'배송비',input_type:'number'},{item_key:'B',section_code:'B',input_type:'boolean'},{item_key:'F',section_code:'E',input_type:'file'},{item_key:'P',section_code:'MEDIA',input_type:'SHOT'}];
const form={answers:{A:'검증 농가',N:'0',B:'미확인',F:'m1'},media:[{upload_id:'m1',status:'REVIEW_REQUIRED'},{shot_code:'P',status:'REJECTED'}]};
test('missing request list excludes received text, zero and attached evidence; includes unknown and rejected photo',()=>{assert.equal(JSON.stringify(F.missing(catalog,form).map(q=>q.item_key)),JSON.stringify(['B','P']));assert.equal(F.progress(catalog,form).done,3);});
test('search locates both field labels and entered answers across sections',()=>{assert.equal(F.questions(catalog,form,{query:'검증 농가'}).length,1);assert.equal(F.questions(catalog,form,{query:'배송비',filter:'done'})[0].item_key,'N');});
test('file reference without actual media is not complete',()=>{assert.equal(F.received(catalog[3],{answers:{F:'missing'},media:[]}),false);});
const secret='test-only-not-a-real-secret-0123456789';
test('session signature rejects forged, malformed and expired cookies',async()=>{const token=await sign({kind:'session',email:'owner@example.test',exp:Date.now()+10000},secret);assert.equal((await verify(token,secret)).email,'owner@example.test');assert.equal(await verify(token+'x',secret),null);assert.equal(await verify(await sign({exp:1},secret),secret),null);assert.equal(await verify('bad',secret),null);});
test('same-origin check rejects cross-site write',()=>{assert.throws(()=>sameOrigin(new Request('https://workspace.test/api/rpc',{headers:{Origin:'https://other.test'}}),{APP_ORIGIN:'https://workspace.test'}));});
test('anonymous RPC rejected before any bridge call',async()=>{const r=await onRequestPost({request:new Request('https://workspace.test/api/rpc',{method:'POST',headers:{Origin:'https://workspace.test'},body:'{}'}),env:{APP_ORIGIN:'https://workspace.test',SESSION_SECRET:secret}});assert.equal(r.status,401);});
test('bridge signs exact request and does not trust caller role',async()=>{const original=globalThis.fetch;let body;globalThis.fetch=async(url,init)=>{body=JSON.parse(init.body);return new Response(JSON.stringify({ok:true,data:{ok:true}}));};try{await bridge({BRIDGE_URL:'https://script.google.com/macros/s/test/exec',BRIDGE_SECRET:secret},'owner@example.test','bootstrap');assert.equal(body.signature,await hmac(body.body,secret));const data=JSON.parse(body.body);assert.equal(data.email,'owner@example.test');assert.equal('role' in data,false);assert.match(data.nonce,/^[a-f0-9]{32}$/);}finally{globalThis.fetch=original;}});
